set term ^ ;

EXECUTE BLOCK  AS
DECLARE stmt VARCHAR(1000);
BEGIN
  FOR
    select 'alter table EGZ_ZALEGLOSCI_UPOMNIENIA drop constraint '||r.rdb$constraint_name||';'
    from rdb$relation_constraints r
    where (r.rdb$constraint_type='FOREIGN KEY') and r.RDB$RELATION_NAME ='EGZ_ZALEGLOSCI_UPOMNIENIA'
    into :stmt
  DO  begin execute statement :stmt; end


END^


set term ; ^


RECREATE TABLE EGZ_UPOMNIENIA (
  ID_UPOMNIENIA BIGINT NOT NULL,
  KOSZT_UPOMNIENIA DECIMAL(18, 4) NOT NULL,
  DATA_UPOMNIENIA TIMESTAMP NOT NULL,
  ADRESAT_ID_OSOBY BIGINT NOT NULL,
  ADRESAT_ID_ADRESU BIGINT NOT NULL,
  ADRESAT_NIP VARCHAR(20),
  ADRESAT_PESEL VARCHAR(20),
  ADRESAT_IMIE VARCHAR(100),
  ADRESAT_NAZWISKO VARCHAR(100),
  ADRESAT_NAZWA VARCHAR(200),
  ADRESAT_MIEJSCOWOSC VARCHAR(100),
  ADRESAT_TYP_ULICY VARCHAR(20),
  ADRESAT_ULICA VARCHAR(100),
  ADRESAT_NR_DOMU VARCHAR(20),
  ADRESAT_NR_LOKALU VARCHAR(20),
  ADRESAT_KOD_POCZTOWY VARCHAR(20),
  ADRESAT_POCZTA VARCHAR(100));


ALTER TABLE EGZ_UPOMNIENIA ADD PRIMARY KEY (ID_UPOMNIENIA);


SET TERM ^ ;

CREATE TRIGGER ID_UPOMNIENIA_AUTOINCREMENT FOR EGZ_UPOMNIENIA
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
                  if(new.id_upomnienia is null) then NEW.ID_UPOMNIENIA = NEXT VALUE FOR ID_UPOMNIENIA_SEQUENCE;
                END^

SET TERM ; ^





RECREATE TABLE EGZ_ZALEGLOSCI (
       ID_ZALEGLOSCI BIGINT NOT NULL,
       ID_NALEZNOSCI BIGINT NOT NULL,
       ID_ZOBOWIAZANIA Integer NOT NULL,
       ID_SYSTEMU_WYMIAROWEGO Integer NOT NULL,
       ID_KONTA_WYMIAROWEGO Integer NOT NULL,
       ID_OSOBY Integer NOT NULL,
       ROK_OBROTOWY Integer NOT NULL,
       RATA Numeric(15,4) NOT NULL,
       ID_RATY Integer NOT NULL,
       KWOTA_ZALEGLOSCI Decimal(15,4) NOT NULL,
       KWOTA_ODSETEK Decimal(15,4),
       TERMIN_PLATNOSCI TIMESTAMP NOT NULL,
       STAWKA_VAT VARCHAR(1),
       ID_UPOMNIENIA Integer,
       PRIMARY KEY (ID_ZALEGLOSCI)
);


RECREATE TABLE EGZ_ZALEGLOSCI_UPOMNIENIA (
  ID_ZALEGLOSCI_UPOMNIENIA BIGINT NOT NULL,
  ID_UPOMNIENIA BIGINT NOT NULL,
  ID_ZALEGLOSCI BIGINT NOT NULL,
  KWOTA_ZALEGLOSCI DECIMAL(18, 4) NOT NULL);


ALTER TABLE EGZ_ZALEGLOSCI_UPOMNIENIA ADD PRIMARY KEY (ID_ZALEGLOSCI_UPOMNIENIA);

ALTER TABLE EGZ_ZALEGLOSCI_UPOMNIENIA ADD FOREIGN KEY (ID_UPOMNIENIA) REFERENCES EGZ_UPOMNIENIA(ID_UPOMNIENIA);

ALTER TABLE EGZ_ZALEGLOSCI_UPOMNIENIA ADD FOREIGN KEY (ID_ZALEGLOSCI) REFERENCES EGZ_ZALEGLOSCI(ID_ZALEGLOSCI);


SET TERM ^ ;

CREATE TRIGGER ID_ZAL_UPOM_AUTO FOR EGZ_ZALEGLOSCI_UPOMNIENIA
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
                  NEW.ID_ZALEGLOSCI_UPOMNIENIA = NEXT VALUE FOR ID_ZAL_UPOM_SEQUENCE;
                END^

SET TERM ; ^


INSERT INTO EGZ_ZALEGLOSCI (ID_ZALEGLOSCI,ID_NALEZNOSCI,ID_ZOBOWIAZANIA,ID_SYSTEMU_WYMIAROWEGO,ID_KONTA_WYMIAROWEGO,ID_OSOBY,ROK_OBROTOWY,RATA,ID_RATY,
TERMIN_PLATNOSCI,KWOTA_ZALEGLOSCI,KWOTA_ODSETEK,STAWKA_VAT,ID_UPOMNIENIA)
VALUES (1,1,14,4096,10001,1009,2019,1,1,'2019-03-31 00:00:00',101,9.33,'N',NULL);
INSERT INTO EGZ_ZALEGLOSCI (ID_ZALEGLOSCI,ID_NALEZNOSCI,ID_ZOBOWIAZANIA,ID_SYSTEMU_WYMIAROWEGO,ID_KONTA_WYMIAROWEGO,ID_OSOBY,ROK_OBROTOWY,RATA,ID_RATY,
TERMIN_PLATNOSCI,KWOTA_ZALEGLOSCI,KWOTA_ODSETEK,STAWKA_VAT,ID_UPOMNIENIA)
VALUES (2,2,14,4096,10001,1009,2019,2,2,'2019-06-30 00:00:00',99.99,9.33,'N',NULL);
INSERT INTO EGZ_ZALEGLOSCI (ID_ZALEGLOSCI,ID_NALEZNOSCI,ID_ZOBOWIAZANIA,ID_SYSTEMU_WYMIAROWEGO,ID_KONTA_WYMIAROWEGO,ID_OSOBY,ROK_OBROTOWY,RATA,ID_RATY,
TERMIN_PLATNOSCI,KWOTA_ZALEGLOSCI,KWOTA_ODSETEK,STAWKA_VAT,ID_UPOMNIENIA)
VALUES (3,3,14,4096,10001,1009,2019,3,3,'2019-09-30 00:00:00',5.40,9.33,'N',NULL);
INSERT INTO EGZ_ZALEGLOSCI (ID_ZALEGLOSCI,ID_NALEZNOSCI,ID_ZOBOWIAZANIA,ID_SYSTEMU_WYMIAROWEGO,ID_KONTA_WYMIAROWEGO,ID_OSOBY,ROK_OBROTOWY,RATA,ID_RATY,
TERMIN_PLATNOSCI,KWOTA_ZALEGLOSCI,KWOTA_ODSETEK,STAWKA_VAT,ID_UPOMNIENIA)
VALUES (4,4,14,4096,10001,1009,2019,4,4,'2019-10-31 00:00:00',3.14159,9.33,'N',NULL);
INSERT INTO EGZ_ZALEGLOSCI (ID_ZALEGLOSCI,ID_NALEZNOSCI,ID_ZOBOWIAZANIA,ID_SYSTEMU_WYMIAROWEGO,ID_KONTA_WYMIAROWEGO,ID_OSOBY,ROK_OBROTOWY,RATA,ID_RATY,
TERMIN_PLATNOSCI,KWOTA_ZALEGLOSCI,KWOTA_ODSETEK,STAWKA_VAT,ID_UPOMNIENIA)
VALUES (5,5,14,4096,10001,1009,2019,5,5,'2019-12-31 00:00:00',12345.6789,9.33,'N',NULL);
commit; 

